### ISSUE TITLE
Inverse parameter order in line 94 in qiskit/qiskit_nwqsim_provider /nwqsim_simulator.py

### ISSUE THREAD

**Issue by Firepanda415** [pnnl/NWQ-Sim#7]
## What is the issue
According to [Python 3.8 doc](https://docs.python.org/3.8/library/functions.html#hasattr)

> hasattr(object, name)
> The arguments are an object and a string. The result is True if the string is the name of one of the object’s attributes, False if not. (This is implemented by calling getattr(object, name) and seeing whether it raises an [AttributeError](https://docs.python.org/3.8/library/exceptions.html#AttributeError) or not.)

But line 94 in the code is
```
if not hasattr(kwarg, self.options):
```
which has clearly reversed order.

## Proof
You can try the following script to see only `hasattr(self.options, kwarg)` can correctly detect if function parameters are the keys of `self.options`.
```
from qiskit.providers import Options

class testObj():
    def __init__(self):
        self.options = Options(shots=1024, seed=2)

    def run(self, circuits, **kwargs):
        for kwarg in kwargs:	
            if not hasattr(self.options, kwarg):
                print("NO attributes for ", kwarg)	
            else:
                print("HAS attributes for ", kwarg)	
        options = {
            'shots': kwargs.get('shots', self.options.shots),
            'seed': kwargs.get('seed', self.options.seed),
        }
        print('options', options)

    def run_inversed(self, circuits, **kwargs):
        for kwarg in kwargs:	
            if not hasattr(kwarg, self.options):
                print("NO attributes for ", kwarg)	
            else:
                print("HAS attributes for ", kwarg)	
        options = {
            'shots': kwargs.get('shots', self.options.shots),
            'seed': kwargs.get('seed', self.options.seed),
        }
        print('options', options)
        
print("Correct order")
testObj().run('circ', shots=1,c=999)

print("\nWrong order")
testObj().run_inversed('circ', shots=1,c=999)
```
This will give output
```
Correct order
HAS attributes for  shots
NO attributes for  c
options {'shots': 1, 'seed': 2}

Wrong order
Traceback (most recent call last):
  File "test.py", line 35, in <module>
    testObj().run_inversed('circ', shots=1,c=999)
  File "test.py", line 21, in run_inversed
    if not hasattr(kwarg, self.options):
TypeError: hasattr(): attribute name must be string
```

## Additional things
I also highly recommand to change line 53 in `qiskit/ghz.py` to
```
job2 = svsim.run(qc,shots=1024,seed=999)
```
So that users have better idea on how and what to customize in `run()`.

**Comment by Firepanda415** [comment]
Closes #8
